spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:prod-db}:${DB_PORT:5432}/authservice_prod
    username: ${DB_USERNAME_PROD:prod_user}
    password: ${DB_PASSWORD_PROD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:30}
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
